VP-92 add functions for endcard tracking issue
stroeer/stroeer-videoplayer pull request #7
Opened 2021-06-22 07:26 UTC by KathleenA

- We need to set all video data as data attribute (setMetaData()) because of tracking issues.

- We have more than one video on a page and we also have a video gallery on giga.de homepage, where videos should be replaced and play by click. I also need the replace and play function in the endcard, so in videoplayer is the global place for this function. 

- added getPosterImage() and setPosterImage()

2021-06-22 07:47 UTC, Tungse requested changes

2021-06-22 07:47 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
I think setAutoplay data attribute is missing here? And also updating the revolver-link is needed?

2021-06-22 08:07 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
autoplay is false when video is replaced, right? Because it was clicked.

2021-06-22 08:11 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
Yes autoplay is false when it is clicked, but true if revolverplay

2021-06-22 08:18 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
ah ok, I would leave setAutoplay() outside of replaceAndPlay() because in videoData is no autoplay information. So I can setAutoplay(true) inside revolverplay function and setAutoplay(false) inside click function. Is it ok for you?

2021-06-22 08:19 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
Or should I add autoplay information to videoData in endcard? And leave it in replaceAndplay()

2021-06-22 08:55 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
I would place all the data-attribute update functions inside the replaceAndPlay function, because it's part of the replacing process. Maybe autoplay as a parameter? Or like you said in videoData.

2021-06-22 09:10 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +  replaceAndPlay = (videoData: IVideoData): void => {
Done.

2021-06-22 10:43 UTC, walialu commented
`getEndcardUrl()` and `setEndcardUrl()` sollten vom Endcard-Plugin zum Videoplayer hinzugefügt werden und nicht schon direkt im Videoplayer selbst vorhanden sein.
Sonst hat der Videoplayer ja eine "harte" Abhängigkeit zu einem Plugin :)

Pseudocode:

```
  init = (StroeerVideoplayer: IStroeerVideoplayer, opts?: any): void => {
    opts = opts ?? {}
    opts.timeout = opts.timeout ?? 5000

    StroeerVideoplayer.setEndcardUrl = () => {
    }
    StroeerVideoplayer.getEndcardUrl = () => {
    }
}
```

Ich kann aber auch gerne von den anderen beiden Reviewern überstimmt werden.

2021-06-22 12:22 UTC, KathleenA commented
> `getEndcardUrl()` and `setEndcardUrl()` sollten vom Endcard-Plugin zum Videoplayer hinzugefügt werden und nicht schon direkt im Videoplayer selbst vorhanden sein.
> Sonst hat der Videoplayer ja eine "harte" Abhängigkeit zu einem Plugin :)
> 
> Pseudocode:
> 
> ```
>   init = (StroeerVideoplayer: IStroeerVideoplayer, opts?: any): void => {
>     opts = opts ?? {}
>     opts.timeout = opts.timeout ?? 5000
> 
>     StroeerVideoplayer.setEndcardUrl = () => {
>     }
>     StroeerVideoplayer.getEndcardUrl = () => {
>     }
> }
> ```
> 
> Ich kann aber auch gerne von den anderen beiden Reviewern überstimmt werden.

Stimmt, ein Video hat nicht zwingend ein Endcard Plugin. Dann würde ich setEndcardUrl() und getEndcardUrl() aus dem videoPlayer nehmen und die endcard setzt die data-endcard-url dann wenn sie replaceAndPlay() nutzt.
Passt das auch für dich @Tungse ?

2021-06-22 13:02 UTC, Tungse commented
> Passt das auch für dich @Tungse ?

Ja, das macht Sinn für mich

2021-06-23 06:32 UTC, Tungse approved these changes

2021-06-23 12:26 UTC, KathleenA commented
@walialu Würde noch auf dein approve warten und dann mergen, falls alles passt.

2021-06-24 18:35 UTC, walialu approved these changes

2021-06-25 07:54 UTC, merged