Feature/vp 90 add hls
stroeer/stroeer-videoplayer pull request #9
Opened 2021-08-12 07:03 UTC by KathleenA

I still have some todos here but you can have a look at it and can say if I have to change something.
I think there will be some `init` function for videoplayer in future where we have to call `loadStreamSource()` but I have not implemented it yet. So `loadStreamSource()` is called in index.html
`loadFirstChunk` is needed to get duration of video to be visible (I tried with hlsConfig option `autoStartLoad: false` but then duration is not visible)
After the first chunk is loaded, `stopLoad()` is called, so `startLoad()` is needed when play event is triggered.
Smb API data has an array of playlists and we must choose one randomly, that's why there is the `getRandomItem` function.

Todos here:
- write new tests and change existing tests to work like before
- test if endcard works correctly with this changes

2021-08-12 07:32 UTC, Tungse requested changes

2021-08-12 07:32 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +      hlsConfig: hlsConfig
Maybe add some default config here, like:
maxBufferSize: 0,
maxBufferLength: 10,
capLevelToPlayerSize: true

2021-08-12 07:32 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +  playlists: string[]
Does this mean that `playlists` is an array of strings?

2021-08-12 07:32 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +      // native support here
If there is nothing implemented here, i would just check 
`
const canPlayNativeHls = videoEl.canPlayType('application/vnd.apple.mpegurl') === 'probably' or videoEl.canPlayType('application/vnd.apple.mpegurl') === 'maybe'`
`if (!canPlayNativeHls and HlsJs.isSupported())`

2021-08-12 07:32 UTC, Tungse commented on src/helper.ts
> +  return arr[Math.floor(Math.random() * arr.length)]
What happens if `arr` is empty? Do you need a check here?

2021-08-12 07:32 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +    this._dataStore.videoEl.innerHTML += `<source src="${playlist}" type="application/x-mpegURL">`
Maybe a check if `playlist` is set here.

2021-08-23 12:20 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +      hlsConfig: hlsConfig
true, done

2021-08-23 12:20 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +  playlists: string[]
yes, I added `?` so that is the mark that it can be undefined

2021-08-23 12:21 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +      // native support here
true done

2021-08-23 12:21 UTC, KathleenA commented on src/helper.ts
> +  return arr[Math.floor(Math.random() * arr.length)]
true, done

2021-08-23 12:26 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +    this._dataStore.videoEl.innerHTML += `<source src="${playlist}" type="application/x-mpegURL">`
No check needed here because you must give a string to this function `setSrc = (playlist: string): void => {` 
else TS will inform you with an error. But I added a check in `replaceAndPlay` if playlists is not undefined because I set it optional in the interface now

2021-08-23 12:40 UTC, walialu approved these changes

2021-08-23 12:46 UTC, Tungse submitted a review, later dismissed
It's sometimes confusing with ds.hls, this._dataStore.hls and just hls .. i guess they are all the same. But beside that, it looks good to me.

2021-08-23 13:03 UTC, jrsmb commented on src/StroeerVideoplayer.ts
> +        ...hlsConfig
Is the order important here or will those three values always be empty in `hlsConfig`?
If not empty I think the `...hlsConfig` would overwrite them again with the ones already existing in `hlsConfig`

2021-08-23 13:50 UTC, jrsmb commented on src/StroeerVideoplayer.ts
> +    this._dataStore.videoEl.innerHTML += `<source src="${playlist}" type="application/x-mpegURL">`
Can line 364 and 365 be combined? String created empty and then added to empty here.
```js
this._dataStore.videoEl.innerHTML = `<source src="${playlist}" type="application/x-mpegURL">`
```

2021-08-24 09:36 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +        ...hlsConfig
This settings are only a default, so you can overwrite them if you set it in hlsConfig, else hlsConfig is empty. I made hlsConfig optional now.

2021-08-24 09:37 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +    this._dataStore.videoEl.innerHTML += `<source src="${playlist}" type="application/x-mpegURL">`
True, done

2021-08-24 09:38 UTC, KathleenA commented
`loadFirstChunk()` should not inside `loadStreamSource` because it'll cause an error if I use `replayeAndPlay()` in Endcard

2021-08-24 10:40 UTC, Tungse requested changes

2021-08-24 10:40 UTC, Tungse commented on src/StroeerVideoplayer.ts
> +    return HlsJs
Should this maybe `this._dataStore.hls`?

2021-08-24 10:42 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +    return HlsJs
@walialu Do you want the hlsInstance `this._dataStore.hls` for other plugins or the module `HlsJs`?

2021-08-25 10:00 UTC, KathleenA commented on src/StroeerVideoplayer.ts
> +    return HlsJs
No, getHlsJs should return the module, not the instance here for other plugins to use Hls without needing it in package.json
Via Slack:
Marco Kellershoff:haus_mit_garten:  11:26 Uhr
Hey, das Modul wollte ich eigentlich haben - habe ich auch kommentiert, dachte ich zumindest

2021-08-25 10:13 UTC, Tungse approved these changes

2021-08-25 10:24 UTC, walialu approved these changes

2021-08-25 10:32 UTC, merged